name: Links

on:
  push:
    paths:
      - '*.md'
  pull_request:
    paths:
      - '*.md'
  schedule:
    - cron:  '0 0 * * SUN'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: --verbose --no-progress *.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
